language: r
r:
  - devel  
dist: xenial

cache:
  packages: true
  directories:
    - $HOME/.npm

latex: false

env:
  global:
    - TZ="Asia/Shanghai"
    - MAKEFLAGS="-j 2"
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

branches:
  only:
    - master
    - develop

pandoc_version: 2.3.1

git:
  depth: 5
  submodules: false
  lfs_skip_smudge: true
  
repos:
  CRAN: https://cloud.r-project.org
#  RForge: https://r-forge.r-project.org
#  inla: https://inla.r-inla-download.org/R/stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: ppa:jeroen/libgit2
      # sudo apt-get install software-properties-common gnupg gnupg-agent
      # sudo add-apt-repository -y ppa:opencpu/libgit2
    packages:
      - g++-8
      # git2r
      - libgit2-dev
      # for pdf output
      - ghostscript
      - imagemagick
      - optipng
      # nloptr
      - libnlopt-dev
      # sf rgdal rgeos
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev


before_install:
  - mkdir ~/.R
  - cp Makevars ~/.R
  - npm install netlify-cli -g
  - curl -fLo /tmp/tinytex.tar.gz https://travis-bin.yihui.name/tinytex.tar.gz
  - tar xzf /tmp/tinytex.tar.gz -C $HOME
  - export PATH=$HOME/.TinyTeX/bin/x86_64-linux:$PATH

before_script:
  - Rscript -e 'update.packages(lib.loc = .libPaths()[1], ask = FALSE)'
  - Rscript -e 'tinytex::tlmgr_install(readLines("latex/TeXLive.pkgs"))'

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

#after_success:
#  - make pdf

deploy:
  provider: script
  script: netlify deploy --prod --dir _book
  skip_cleanup: true
  on:
    branch: master
