# 广义线性混合效应模型 {#Generalized-Linear-Mixed-Models}

- rr2: R2s for Regression Models

Three methods to calculate R2 for models with correlated errors, including Phylogenetic GLS, Phylogenetic Logistic Regression, Linear Mixed Models (LMMs), and Generalized Linear Mixed Models (GLMMs). See details in Ives 2018 <doi:10.1093/sysbio/syy060>.

	https://github.com/arives/rr2
	
- r2glmm: Computes R Squared for Mixed (Multilevel) Models

https://mirrors.tuna.tsinghua.edu.cn/CRAN/web/packages/r2glmm/index.html

The model R squared and semi-partial R squared for the linear and generalized linear mixed model (LMM and GLMM) are computed with confidence limits. The R squared measure from Edwards et.al (2008) <doi:10.1002/sim.3429> is extended to the GLMM using penalized quasi-likelihood (PQL) estimation (see Jaeger et al. 2016 <doi:10.1080/02664763.2016.1193725>). Three methods of computation are provided and described as follows. First, The Kenward-Roger approach. Due to some inconsistency between the 'pbkrtest' package and the 'glmmPQL' function, the Kenward-Roger approach in the 'r2glmm' package is limited to the LMM. Second, The method introduced by Nakagawa and Schielzeth (2013) <doi:10.1111/j.2041-210x.2012.00261.x> and later extended by Johnson (2014) <doi:10.1111/2041-210X.12225>. The 'r2glmm' package only computes marginal R squared for the LMM and does not generalize the statistic to the GLMM; however, confidence limits and semi-partial R squared for fixed effects are useful additions. Lastly, an approach using standardized generalized variance (SGV) can be used for covariance model selection. Package installation instructions can be found in the readme file.

- cAIC4: Conditional Akaike Information Criterion for 'lme4'

Provides functions for the estimation of the conditional Akaike information in generalized mixed-effect models fitted with (g)lmer() from 'lme4'.

- lme4: Linear Mixed-Effects Models using 'Eigen' and S4

Fit linear and generalized linear mixed-effects models. The models and their components are represented using S4 classes and methods. The core computational algorithms are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen' "glue".

  https://github.com/lme4/lme4/

- glmmTMB: Generalized Linear Mixed Models using Template Model Builder

Fit linear and generalized linear mixed models with various extensions, including zero-inflation. The models are fitted using maximum likelihood estimation via 'TMB' (Template Model Builder). Random effects are assumed to be Gaussian on the scale of the linear predictor and are integrated out using the Laplace approximation. Gradients are calculated using automatic differentiation.

  https://github.com/glmmTMB

- fitting mixed models with (temporal) correlations in R 时间相依的结构的 GLMMs及其实现 [作者 Github](https://github.com/bbolker) 主页 <https://bbolker.github.io/mixedmodels-misc/notes/corr_braindump.html>

- Broadening Your Statistical Horizons: Generalized Linear Models and Multilevel Models <https://bookdown.org/roback/bookdown-bysh/>


- gllvm: Generalized Linear Latent Variable Models

Generalized linear latent variable model (gllvm) for analyzing multivariate data. Estimation is performed using either Laplace approximation or variational approximation method implemented via TMB

- gllm: Generalised log-Linear Model

Routines for log-linear models of incomplete contingency tables, including some latent class models, via EM and Fisher scoring approaches. Allows bootstrapping. See Espeland and Hui (1987) <doi:10.2307/2531553> for general approach.


- FENmlm: Fixed Effects Nonlinear Maximum Likelihood Models

Efficient estimation of maximum likelihood models with multiple fixed-effects. Standard-errors can easily and flexibly be clustered and estimations exported [@Laurent_2018_Efficient].

- ggeffects: Tidy Data Frames of Marginal Effects for ggplot2

Compute marginal effects from statistical models and returns the result as tidy data frames. These data frames are ready to use with the 'ggplot2'-package. Marginal effects can be calculated for many different models. Interaction terms, splines and polynomial terms are also supported. The two main functions are ggpredict() and ggeffect(). There is a generic plot()-method to plot the results using 'ggplot2'.

https://github.com/strengejacke/ggeffects

- broom: Convert Statistical Analysis Objects into Tidy Tibbles

Summarizes key information about statistical objects in tidy tibbles. This makes it easy to report results, create plots and consistently work with large numbers of models at once. Broom provides three verbs that each provide different types of information about a model. tidy() summarizes information about model components such as coefficients of a regression. glance() reports information about an entire model, such as goodness of fit measures like AIC and BIC. augment() adds information about individual observations to a dataset, such as fitted values or influence measures.

H-likelihood [@Lee_2018_Generalized]

- DHARMa: Diagnostics for HierArchical Regession Models

https://github.com/florianhartig/DHARMa

The 'DHARMa' package uses a simulation-based approach to create readily interpretable scaled (quantile) residuals for fitted generalized linear mixed models. Currently supported are generalized linear mixed models from 'lme4' (classes 'lmerMod', 'glmerMod'), generalized additive models ('gam' from 'mgcv'), 'glm' (including 'negbin' from 'MASS', but excluding quasi-distributions) and 'lm' model classes. Alternatively, externally created simulations, e.g. posterior predictive simulations from Bayesian software such as 'JAGS', 'STAN', or 'BUGS' can be processed as well. The resulting residuals are standardized to values between 0 and 1 and can be interpreted as intuitively as residuals from a linear regression. The package also provides a number of plot and test functions for typical model misspecification problems, such as over/underdispersion, zero-inflation, and residual spatial and temporal autocorrelation.

- bernor: Logit-Normal generalized linear mixed models (GLMM) using ordinary, independent and identically distributed Monte Carlo. 

Bernoulli Regression with Normal Random Effects (R package, not on CRAN)

https://github.com/cjgeyer/bernor

http://www.stat.umn.edu/geyer/bernor/
Monte Carlo likelihood inference for missing data models [@Sung_2007_Monte]

- qle: Simulation-Based Quasi-Likelihood Estimation

A simulation-based quasi-likelihood method (Baaske, M., Ballani, F., v.d. Boogaart, K.G. (2014)) for parameter estimation of parametric statistical models for which closed-form representations of distributional characteristics are unavailable and can only be obtained by computationally intensive simulations of the model.

- 带一个高斯随机效应的泊松广义线性混合效应模型 A Gentle Stan vs. INLA Comparison

[A Gentle Stan vs. INLA Comparison](http://www.martinmodrak.cz/2018/02/02/a-gentle-stan-vs.-inla-comparison/)


关于广义线性混合效应模型的高频问题 FAQ <https://bbolker.github.io/mixedmodels-misc/glmmFAQ.html>

广义线性混合效应模型之贝叶斯模型选择

- 作者主页 https://www.mn.uio.no/math/english/people/aca/aliaksah/
- 代码 https://github.com/aliaksah/EMJMCMC2016

 <https://github.com/florianhartig/BayesianTools>
<https://cran.r-project.org/web/packages/BayesianTools/index.html>

General-purpose MCMC and SMC samplers, as well as plot and diagnostic functions for Bayesian statistics, with a particular focus on calibrating complex system models. Implemented samplers include various Metropolis MCMC variants (including adaptive and/or delayed rejection MH), the T-walk, two differential evolution MCMCs, two DREAM MCMCs, and a sequential Monte Carlo (SMC) particle filter.

提供很多的采样器
详细介绍
<https://florianhartig.github.io/LearningBayes/>

Estimating treatment effects and ICCs from (G)LMMs on the observed scale using Bayes, Part 1: lognormal models

- [Estimating treatment effects and ICCs from (G)LMMs on the observed scale using Bayes, Part 1: lognormal models](http://rpsychologist.com/GLMM-part1-lognormal)

R2jags 包作者 Yu-Sung Su 苏毓松

blme: Bayesian Linear and Generalized Linear Mixed-Effects Models

两个主要函数
- blmer
- bglmer

频率派
lme4 包
- lmer
只拟合线性混合效应模型
Fit a linear mixed-effects model (LMM) to data, via REML or maximum likelihood.
- glmer
只拟合广义线性混合效应模型
Fitting Generalized Linear Mixed-Effects Models

lm for linear models; glmer for generalized linear; and nlmer for nonlinear mixed models.

 glm for Generalized Linear Models (without random effects)

- glmmTMB

glmmTMB: Generalized Linear Mixed Models using Template Model Builder

blme: Bayesian Linear Mixed-Effects Models
Maximum a posteriori estimation for linear and generalized linear mixed-effects models in a Bayesian setting. Extends 'lme4' by Douglas Bates, Martin Maechler, Ben Bolker, and Steve Walker.


blmeco: Data Files and Functions Accompanying the Book "Bayesian Data Analysis in Ecology using R, BUGS and Stan"
Data files and functions accompanying the book Korner-Nievergelt, Roth, von Felten, Guelat, Almasi, Korner-Nievergelt (2015) "Bayesian Data Analysis in Ecology using R, BUGS and Stan", Elsevier, New York.

@Book{blmeco,
    title = {Bayesian Data Analysis in Ecology using Linear Models with R, BUGS and Stan},
    author = {Fraenzi Korner-Nievergelt and Tobias Roth and Stefanie {von Felten} and Jerome Guelat and Bettina Almasi and Pius Korner-Nievergelt},
    year = {2015},
    publisher = {Elsevier},
  }

BRugs: Interface to the 'OpenBUGS' MCMC Software
Fully-interactive R interface to the 'OpenBUGS' software for Bayesian analysis using MCMC sampling. Runs natively and stably in 32-bit R under Windows. Versions running on Linux and on 64-bit R under Windows are in "beta" status and less efficient.  
  
@Article{BRugs2006,
    title = {Making BUGS Open},
    author = {Andrew Thomas and Bob O'Hara and Uwe Ligges and Sibylle Sturtz},
    journal = {R News},
    year = {2006},
    pages = {12--17},
    number = {1},
    volume = {6},
    url = {https://cran.r-project.org/doc/Rnews/},
  }
  
  
  
glmmBUGS: Generalised Linear Mixed Models with BUGS and JAGS
Automates running Generalized Linear Mixed Models, including spatial models, with WinBUGS, OpenBUGS and JAGS. Models are specified with formulas, with the package writings model files, arranging unbalanced data in ragged arrays, and creating starting values. The model is re-parameterized, and functions are provided for converting model outputs to the original parameterization.

@Article{glmmBUGS,
    title = {{MCMC} for Generalized Linear Mixed Models with {glmmBUGS}},
    author = {Patrick E Brown and L Zhou},
    journal = {R Journal},
    year = {2010},
    volume = {2},
    url = {http://journal.r-project.org/archive/2010-1/RJournal_2010-1_Brown+Zhou.pdf},
  }


R2OpenBUGS: Running OpenBUGS from R
Using this package, it is possible to call a BUGS model, summarize inferences and convergence in a table and graph, and save the simulations in arrays for easy access in R.

@Article{R2WinBUGS,
    title = {R2WinBUGS: A Package for Running WinBUGS from R},
    author = {Sibylle Sturtz and Uwe Ligges and Andrew Gelman},
    journal = {Journal of Statistical Software},
    year = {2005},
    pages = {1--16},
    number = {3},
    volume = {12},
    url = {http://www.jstatsoft.org},
  }

  



