---
title: "临时存放的笔记"
output: 
  pdf_document: 
    extra_dependencies:
      ctex: UTF8  
    latex_engine: xelatex
    number_sections: yes
    toc: yes
classoption: "b5paper"
---

```{r setup, include=FALSE}
knitr::knit_hooks$set(
  optipng = knitr::hook_optipng,
  pdfcrop = knitr::hook_pdfcrop,
  small.mar = function(before, options, envir) {
    # smaller margin on top and right
    if (before) par(mar = c(4.1, 4.1, 0.5, 0.5), family = "Times")  
  }
)
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  echo = TRUE,
  cache = TRUE,
  small.mar = TRUE,
  out.width = "70%",
  fig.align = "center",
  fig.width = 6,
  width = 69,
  fig.asp = 0.618
)
is_on_travis = identical(Sys.getenv("TRAVIS"), "true")
is_online = curl::has_internet()
options(
  digits = 3,
  citation.bibtex.max = 999,
  bitmapType = "cairo",
  stringsAsFactors = FALSE,
  BioC_mirror = "https://mirrors.tuna.tsinghua.edu.cn/bioconductor",
  repos = c(
    CRAN = if(is_on_travis) "https://cloud.r-project.org" else "https://mirrors.tuna.tsinghua.edu.cn/CRAN/",
    RForge = "https://r-forge.r-project.org",
    inla = "https://inla.r-inla-download.org/R/stable"
  ),
  knitr.graphics.auto_pdf = FALSE,
  width = 69,
  str = strOptions(strict.width = "cut"),
  tikzDefaultEngine = "pdftex",
  tikzLatexPackages = c(
    "\\usepackage{tikz}",
    "\\usepackage[active,tightpage,psfixbb]{preview}",
    "\\PreviewEnvironment{pgfpicture}",
    "\\setlength\\PreviewBorder{0pt}",
    "\\usepackage[colorlinks, breaklinks]{hyperref}",
    "\\usepackage{amsmath,amsfonts,mathrsfs,times}"
  )
)
lapply(c('tikzDevice','car','IM'), function(pkg) {
  if (system.file(package = pkg) == '') install.packages(pkg)
})
```

# 前言 {#preface}


支持缩放和拖拽的交互可视化 三维地球上

- Building an Interactive Globe Visualization in R [threejs][r-threejs]

[r-threejs]: https://www.displayr.com/interactive-globe-r/

```{r child = 'ch1/rmarkdown.Rmd'}
```
